"""empty message

Revision ID: 358266df28a3
Revises: 
Create Date: 2024-06-07 21:13:23.687024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358266df28a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chicken', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['chicken'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('chicken')

    # ### end Alembic commands ###
